version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis_0
    ports:
      - 6190:6379
    volumes:
      - ./volumes/redis_0/data:/data
    networks:
      - network_0

networks:
  network_0:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
