services:
  redis:
    image: redis:latest
    container_name: redis_0
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis_0/data:/data
    networks:
      - seckill_network_0

networks:
  seckill_network_0:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
