name: Deploy Project Seckill
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVER_IP: "139.155.80.149"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH known hosts
        run: |
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

      - name: Deploy seckill nginx
        run: |
          scp -r ./seckill-nginx/* ubuntu@$SERVER_IP:~/seckill/nginx
