name: Deploy Seckill
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH known hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy seckill docker
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} "cd ~/seckill/docker && docker compose down"
          scp -r ./seckill-docker/* ubuntu@${{ secrets.SERVER_IP }}:~/seckill/docker
          ssh ubuntu@${{ secrets.SERVER_IP }} "cd ~/seckill/docker && docker compose up -d"

      - name: Deploy seckill nginx
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} "cd ~/seckill/nginx && /usr/local/openresty/nginx/sbin/nginx -p \$(pwd) -s stop" || echo "nginx stop failed"
          scp -r ./seckill-nginx/* ubuntu@${{ secrets.SERVER_IP }}:~/seckill/nginx
          ssh ubuntu@${{ secrets.SERVER_IP }} "cd ~/seckill/nginx && /usr/local/openresty/nginx/sbin/nginx -p \$(pwd) -c conf/nginx.conf"
